import uuid
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Integer
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from backend.database import Base

class Message(Base):
    __tablename__ = "messages"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()), index=True)

    # Which chat this message belongs to
    chat_id = Column(String, ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True)

    # "user" = question typed by the human
    # "assistant" = response generated by Gemini
    role = Column(String, nullable=False)  # "user" | "assistant"

    # The actual text content of the message
    # Text type = unlimited length (unlike String which caps at 255)
    content = Column(Text, nullable=False)

    # Order of messages within a chat (1, 2, 3...)
    # Used on Day 16 to pick the last N messages for memory
    sequence = Column(Integer, nullable=False, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationship back to chat
    chat = relationship("Chat", back_populates="messages")

    def __repr__(self):
        return f"<Message id={self.id} role={self.role} chat_id={self.chat_id}>"